### ISSUE TITLE
Interface initialization change

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3-python-interface#1]
I don't like this.  While it is simple to do in Python and probably about the same for node.js, it is significantly more complex to handle this in 'C'

self.pg3init = json.loads(
                base64.b64decode(os.environ.get('PG3INIT')))

Grabbing the information from STDIN is reasonably easy to do in any language.

What is the quantified change in reliability that prompted this change?

**Comment by Einstein42** [comment]
I incorporated both. ENV will be preferred however I added back in STDIN

**Comment by bpaauwe** [comment]
Thanks!  That will make implementing a 'C' interface library a lot easier.    Still curious why the bas64 encode? Are there plans to have binary data in there?
